language: node_js
node_js:
  - 10
cache:
  - npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/  
  github_token: $GITHUB_API_KEY
  target-branch: master
  on:
    all_branches: true
