language: node_js
node_js:
  - 10
cache:
  - npm
install:
  - npm install
script:
  - npm run build
deploy:
  target-branch: master
  provider: pages
  skip_cleanup: true
  local_dir: build/  
  github_token: $GITHUB_API_KEY
