language: node_js
node_js:
  - 10
cache:
  - npm
install:
  - npm install
script:
  - npm run build
deploy:
  repo: ShaneGravestock.github.io
  provider: pages
  skip_cleanup: true
  local_dir: build/  
  api_key: $GITHUB_API_KEY
  on:
    branch: master
